// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdifnkyrdmrougkhyybu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkaWZua3lyZG1yb3Vna2h5eWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzUxMTcsImV4cCI6MjA2MzkxMTExN30.G-mO0Xe1hf7BbU51GW7VZ6yWgPBSNQ_6EBHc8ebDXGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);